src/wadl/rax-cloudFiles-api-v1.wadl:
    title: Rackspace Cloud Files™ Developer Guide
    output_directory: rst/api-operations/cloud-files
    
src/wadl/rax-cloudFilesCDN-api-v1.wadl:
    title: Rackspace Cloud Files™ Developer Guide
    output_directory: rst/api-operations/cloud-files-cdn   